### ISSUE TITLE
No `.Rnw` source file to look over if there is confusion

### ISSUE THREAD

**Issue by lwjohnst86** [mkoohafkan/kfigr#2]
Hi, just trying to understand how `kfigr` works. In the vignette, at the bottom is says "If there is any confusion, look to the .Rnw source file and all should be clear". But there is no `.Rnw` source file for me to look at!

**Comment by mkoohafkan** [comment]
Thanks for catching this typo---I am in fact referring to the Rmd file, which is the vignette you read. Use `browseVignettes("kfigr")` and click on 'source' to get the Rmd file, which you could `knit` yourself to reproduce the vignette. Rnw is the file extension for Sweave (LaTeX + R). If you're making an Rnw file there is no need for `kfigr` as LaTeX has its own figure and table referencing system.

**Comment by lwjohnst86** [comment]
Ah, gotcha. Not sure why I didn't get that you were referring to the 
.Rmd file right away... oopps! Thanks!
