### ISSUE TITLE
.docx implementation?

### ISSUE THREAD

**Issue by simonthelwall** [mkoohafkan/kfigr#3]
Really nice package. Do you have any plans for a .docx implementation? It would be massively useful.

**Comment by mkoohafkan** [comment]
Thanks Simon! I'm not sure how I would go about a .docx implementation. What workflow do you have in mind? The only way I know to go from .md to .docx would be via `pandoc`. `kfigr` generates [anchor links](http://www.echoecho.com/htmllinks08.htm) in a markdown document, so it sounds like the real need is for `pandoc` to support conversion of anchor links to .docx cross-references---quite beyond the scope of `kfigr`, I'm afraid.

**Comment by simonthelwall** [comment]
I found the [R captioner](https://github.com/adletaw/captioner) package which produces docx cross references, so that solves my problem. Thanks.
